{
 "title": "gantrycrane",
 "description": "Dashboard for the gantrycrane validation demo",
 "time": { "from": "2023-06-19T14:13:09.565Z", "to": "2023-06-19T14:13:20.442Z" },
 "templating": {
  "list": [
   { "name": "quantity", "query": "select name from quantity;" },
   {
    "name": "machine_id",
    "query": "select machine_id from machine where name = $machine;"
   },
   {
    "name": "run_id",
    "query": "select run_id from run where machine_id = (select machine_id from machine where name = '$machine')"
   },
   { "name": "machine", "query": "select name from machine;" },
   {
    "name": "num_replications",
    "query": "select num_replications from simulation where machine_id = $machine_id and run_id = $run_id;"
   },
   {
    "name": "replication_nr",
    "query": "select replication_nr from simulationdatapoint where machine_id = $machine_id and run_id = $run_id;"
   }
  ]
 },
 "panels": [
  { "title": "Traces over time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$quantity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "repeat": "quantity",
   "targets": [
    {
     "rawSql": "SELECT ts, value as \"Real-world measurement\"\r\nFROM measurement \r\nWHERE machine_id = $machine_id \r\n  AND quantity = $quantity \r\n  AND run_id = $run_id;"
    },
    {
     "rawSql": "SELECT ts, \r\nMIN(value) as \"Simulation minimum\", \r\nMAX(value) as \"Simulation maximum\", \r\nAVG(value) as \"Simulation average\"\r\nFROM simulationdatapoint\r\nWHERE machine_id = $machine_id \r\n  AND quantity = $quantity \r\n  AND run_id = $run_id \r\nGROUP BY ts;"
    },
    {
     "rawSql": "select ts, value as \"target trajectory\"\r\nfrom trajectory \r\nWHERE machine_id = $machine_id \r\nand quantity = $quantity  \r\nand run_id = $run_id;"
    }
   ]
  },
  { "title": "Root-Mean-Square Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "position RMSE gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM rootmeansquarederror, quantity \r\nwhere name = 'position' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "velocity RMSE gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM rootmeansquarederror, quantity \r\nwhere name = 'velocity' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "angular position RMSE gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM rootmeansquarederror, quantity \r\nwhere name = 'angular position' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "angular velocity RMSE gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM rootmeansquarederror, quantity \r\nwhere name = 'angular velocity' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Root-Mean-Square Error ",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT run_id, quantity, MIN(distance), MAX(distance), AVG(distance), unit  FROM rootmeansquarederror, quantity where quantity  = name GROUP BY run_id, quantity, unit ORDER BY run_id DESC, quantity ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "$quantity RMSE",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 41 },
   "repeat": "quantity",
   "targets": [
    {
     "rawSql": "SELECT ts, quantity, distance as \"$quantity RMSE\", unit FROM rootmeansquarederror, quantity WHERE quantity = $quantity and run_id = $run_id and quantity = name;"
    }
   ]
  },
  {
   "title": "Normalized Euclidean Distance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "$quantity Normalized Euclidean Distance",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
     "repeat": "quantity",
     "targets": [
      {
       "rawSql": "SELECT ts, quantity, distance as \"$quantity Normalized Euclidean distance\", unit FROM normalizedeuclideandistance, quantity WHERE quantity = $quantity and run_id = $run_id and quantity = name;"
      }
     ]
    },
    {
     "title": "position Normalized Euclidean gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), Max(distance), AVG(distance), unit  \r\nFROM normalizedeuclideandistance, quantity \r\nwhere name = 'position' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    },
    {
     "title": "velocity Normalized Euclidean gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM normalizedeuclideandistance, quantity \r\nwhere name = 'velocity' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    },
    {
     "title": "angular position Normalized Euclidean gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM normalizedeuclideandistance, quantity \r\nwhere name = 'angular position' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    },
    {
     "title": "angular velocity Normalized Euclidean gauge",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), AVG(distance), unit  \r\nFROM normalizedeuclideandistance, quantity \r\nwhere name = 'angular velocity' and quantity  = name and run_id = $run_id \r\nGROUP BY run_id, quantity, unit \r\nORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    },
    {
     "title": "Normalized Euclidean Distance",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), MAX(distance), AVG(distance), unit  FROM normalizedeuclideandistance, quantity where quantity  = name GROUP BY run_id, quantity, unit ORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    },
    {
     "title": "Total Normalized Euclidean Distance",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "rawSql": "SELECT run_id, quantity, MIN(distance), MAX(distance), AVG(distance), unit  FROM totalnormalizedeuclideandistance, quantity where quantity  = name GROUP BY run_id, quantity, unit ORDER BY run_id DESC, quantity ASC LIMIT 50 "
      }
     ]
    }
   ]
  },
  {
   "title": "Mahalanobis Distance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mahalanobis Distance",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "rawSql": "select run_id, quantity, distance\r\nfrom mahalanobisdistance\r\nWHERE machine_id = 1\r\norder by run_id DESC, quantity ASC\r\nLIMIT 50;"
      }
     ]
    }
   ]
  },
  { "title": "Frequentist Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "$quantity mean confidence bounds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 66 },
   "repeat": "quantity",
   "targets": [
    {
     "rawSql": "SELECT ts, quantity, mu_lower, mu_upper, unit FROM frequentistmetric, quantity WHERE quantity = $quantity and run_id = $run_id and quantity = name;"
    }
   ]
  },
  {
   "title": "$quantity error confidence bounds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 88 },
   "repeat": "quantity",
   "targets": [
    {
     "rawSql": "SELECT ts, quantity, error_lower, error_upper, unit FROM frequentistmetric, quantity WHERE quantity = $quantity and run_id = $run_id and quantity = name;"
    }
   ]
  },
  {
   "title": "Global Frequentist Metric",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "select run_id, quantity, average_relative_error, average_relative_confidence_indicator, maximum_relative_error\r\nfrom globalfrequentistmetric \r\nWHERE machine_id = 1\r\norder by run_id DESC, quantity ASC\r\nLIMIT 50;"
    }
   ]
  }
 ]
}