{
 "title": "harbour-viz",
 "description": "Harbour vizualisation of boat and quay using canvas panels",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "id",
    "query": "select machine_id from machine;"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "canvas",
   "gridPos": { "h": 17, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT slot, state FROM quay where machine_id = $id ORDER BY slot LIMIT 50 "
    },
    {
     "rawSql": "SELECT slot, container_id FROM quay where machine_id = $id ORDER BY slot LIMIT 50 "
    }
   ]
  },
  {
   "title": "Boat State",
   "type": "canvas",
   "gridPos": { "h": 17, "w": 9, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT slot, state FROM cargomanifest where ship_id = $id ORDER BY slot LIMIT 50 "
    },
    {
     "rawSql": "SELECT slot, container_id FROM cargomanifest where ship_id = $id ORDER BY slot LIMIT 50 "
    }
   ]
  },
  {
   "title": "Roll",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select roll from ship where id = $id;"
    }
   ]
  },
  {
   "title": "Draft",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select draft from ship where id = $id;"
    }
   ]
  }
 ]
}